spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_ID}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

logging:
  level:
    root: DEBUG

server:
  servlet:
    context-path: /api/v1